---
- name: "Do prechecks"
  ansible.builtin.import_tasks:
    file: "./prechecks.yaml"
  tags: "prechecks"

- name: "Remove old installation of kvm and minikube"
  ansible.builtin.import_tasks:
    file: "./remove_old_installation"
  tags: "clear"

- name: "Install kvm and minikube"
  ansible.builtin.import_tasks:
    file: "./install_needed_components"
  tags: "install"
